### ISSUE TITLE
How to test that exported types haven't been changed?

### ISSUE THREAD

**Issue by the-spyke** [TypeStrong/ts-expect#17]
Hi, i'd like to test that exported types haven't been changed:

```ts
import type * as typeExports from './index';
import * as codeExports from './index';

test('Exports should be stable', () => {
  expect(codeExports).toMatchSnapshot();
  expect(typeExports).toMatchSnapshot();
});
```

Is there a way to do it?

**Comment by blakeembrey** [comment]
Not using this package, but in theory you could probably make a test that that this reading the built `.d.ts` file. But then imports could change, so that won't always work. Another approach could be doing this and defining the shape of the exports, but I'll have to leave that as an exercise to the reader.
