### ISSUE TITLE
FYI: type-plus

### ISSUE THREAD

**Issue by unional** [TypeStrong/ts-expect#2]
Hi Blake,

FYI the [`type-plus`](https://github.com/unional/type-plus) library also have some type assertion tools available. Just in case you need some. :)

**Comment by blakeembrey** [comment]
Thanks! I'm discovering a lot of different people have built similar things 😄 I'll probably be keeping this simple without any runtime so I can implement https://github.com/TypeStrong/ts-expect/issues/1 but the nice thing is this library can use whatever types anyone else has built already (because it's a very simply library really!).
