### ISSUE TITLE
False errors when checking enums

### ISSUE THREAD

**Issue by johan13** [TypeStrong/ts-expect#27]
I would expect all three of these to pass, but only one of them does:

```ts
import { expectType, TypeEqual } from "ts-expect";

enum Foo { Alpha, Beta }

const foo1      = Foo.Alpha;
const foo2: Foo = Foo.Alpha;
const foo3      = Foo.Alpha as Foo;

expectType<TypeEqual<Foo, typeof foo1>>(true); // Not OK
expectType<TypeEqual<Foo, typeof foo2>>(true); // Not OK
expectType<TypeEqual<Foo, typeof foo3>>(true); // OK
```

I am using ts-expect 1.3.0 and Typescript 4.7.3 in strict mode.

**Comment by blakeembrey** [comment]
I think this is the correct behavior and comes down to how the TypeScript compiler works. For `foo1` and `foo2`, TypeScript sees the values as `Foo.Alpha` so they don't equal. But you explicitly override the type in `foo3` which is why it has a different behavior.

**Comment by blakeembrey** [comment]
I think the second example comes down to TypeScript flow analysis, since changing it to `let` still evaluates it to `Foo.Alpha`. The only way to make it uncertain, so "OK", so to do something like this:

```ts
enum Foo { Alpha, Beta }

let foo2: Foo = Foo.Alpha;

if (Math.random() > 0.5) {
  foo2 = Foo.Beta;
}

expectType<TypeEqual<Foo, typeof foo2>>(true);
```

You can change the random if to `if (true)` or `if (false)` and see that TypeScript again has the constant value as the type.
