### ISSUE TITLE
Yes but what's it actually for?...

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/ts-expect#3]
Hey @blakeembrey ,

Super cool to see you're doing something new! I've read and re-read the README.md and I'm afraid I can't work out what you would use ts-expect for....

Any chance you could expand on the why and perhaps explain what problems ts-expect is solving? I've no doubt there's a solid need for this but since I can't understand what it is I don't actually know.

Maybe this is something I need in my life as well?

**Comment by blakeembrey** [comment]
This is a really good question and I could use help answering it myself so I have a better understanding how to position and describe this modules use cases.
 
1. Testing for `.d.ts` files is the easy one - now you could write a test suite like you’d do with 
https://github.com/Microsoft/dtslint but on your JS modules. E.g. create a test file, use this library for type assertions, then run the compiler over the test file to make sure the definition is correct.
2. This is the one that’s harder to explain. Do you ever have cases where you have a union type and some sort of switching logic based on a property of the union? In these cases, how do you test that your code has actually exhausted every possible type union? The simple use case here is that you throw in a never assertion and let the compiler let you know if you missed a use case.

The `TypeOf` type was actually just a special subset of case 2. I have a function that does “validate some loose JSON input”. I wanted to make sure, given the input of a string, I had compared it to every defined string the type system knows about. In this case, it’s an early warning system - if you added to the union of allowed types at some point, your code is still technically correct even if the thing making this validation doesn’t handle the new type because the result is still a subset of the union. In these cases, I’d like it if the compiler still yelled at me so I remember to go update those loose validation functions. 

Happy to add more concrete examples tomorrow if this doesn’t make sense. The README case is really a dumbed down (maybe too dumb?) explanation of case 2.

**Comment by johnnyreilly** [comment]
I'm afraid I'm still going "yeah.... But what is it?" 😄

Sorry - I'm a simple soul and I'm just not getting this. It feels like you know the basic problem that ts-expect exists to solve and you're talking around variations on that them, whilst I'm wondering "what prompted this in the first place? / What's the basic problem?" 

I think it would be useful to understand, with an example, what the problem is. Who is the expected user of this module? How does this fit in alongside things like jest / mocha etc Or if it doesn't fit there at all - well that's interesting....

Apologies that I'm not getting "it". But I think it's fairly likely that if I'm not others may not as well

**Comment by blakeembrey** [comment]
Makes sense. Stepping back, the basic problem is testing types (opposed to testing code). This is a simple way to test types as you would in something like dtslint. I see two use cases in my own experience where you want to test types:

1. You’re writing a definition for your JavaScript library and you want to check it’s correct. E.g. 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/buffer-from/buffer-from-tests.ts but you can write this and rely on the TypeScript compiler instead of comment parsing.
2. You’re writing some code in a project and you want to make sure a type is always what you expect it to be. Can you recall a use-case where you must accept a looser type than the type system defines (e.g. deserializing a string from IO without validation)? You accept a string but want to check a specific string in a union type. You can use this after the if condition to ensure you captured the checks you want in case you expand the union later.

It may help to remember that for case 2, it’s relying on TypeScript narrowing the type outside the if condition. So in the examples in the README, it fails because the input string was either narrowed only to a single word, or not narrowed to never (e.g. didn’t exhaust all the possible cases of the union). I’ll pull out the specific example I’m using later if it still doesn’t make sense.

**Comment by johnnyreilly** [comment]
> You’re writing a definition for your JavaScript library and you want to check it’s correct. E.g.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/buffer-from/buffer-from-tests.ts but you can write this and rely on the TypeScript compiler instead of comment parsing.

This is interesting. So what you're saying is using ts-expect you could write the following dtslint tests using code rather than comments?

```
import bufferFrom = require('buffer-from');

bufferFrom([1, 2, 3, 4]); // $ExpectType Buffer
bufferFrom(new Uint8Array([1, 2, 3, 4]).buffer, 1, 2); // $ExpectType Buffer
bufferFrom('test', 'utf8'); // $ExpectType Buffer
bufferFrom(bufferFrom('test')); // $ExpectType Buffer
```

That's cool! How would the above look written using ts-expect?

~Side question: definitely typed tests have traditionally been "compilation tests". That is to say: there's no concept of individual tests running and passing/failing as such. Rather, if a test file doesn't compile that's a "failing test". It's kinda brute force but it functions.~

~Does ts-expect make it possible to write these sorts of tests as actual tests?~ I realize it doesn't.

I didn't understand the second example I'm afraid. You mean you'd use ts-expect at runtime in an application?

**Comment by blakeembrey** [comment]
@johnnyreilly For the first example, you can write:

```ts
import bufferFrom = require('buffer-from');

expectType<Buffer>(bufferFrom([1, 2, 3, 4]));
expectType<Buffer>(bufferFrom(new Uint8Array([1, 2, 3, 4]).buffer, 1, 2));
expectType<Buffer>(bufferFrom('test', 'utf8'));
expectType<Buffer>(bufferFrom(bufferFrom('test')));
```

Here's my specific example where I use the second use case:

```ts
export function expandConfig(config: Config): CoreConfig {
  // Core configs.
  if (config.type === "oidc" || config.type === "oauth2") return config;

  // Preconfigured OAuth 2 configurations.
  if (config.type === "known-connection") {
    if (config.name === "github") {
      return {
        type: "oauth2",
        title: config.title || "GitHub",
        authorizationUri: "https://github.com/login/oauth/authorize",
        accessTokenUri: "https://github.com/login/oauth/access_token",
        clientId: config.clientId,
        clientSecret: config.clientSecret,
        profileUri: "https://api.github.com/user",
        subjectPointer: "/id"
      };
    }

    if (config.name === "google") {
      return {
        type: "oidc",
        title: config.title || "Google",
        authorizationUri: "https://accounts.google.com/o/oauth2/v2/auth",
        accessTokenUri: "https://oauth2.googleapis.com/token",
        clientId: config.clientId,
        clientSecret: config.clientSecret,
        issuer: "https://accounts.google.com/",
        scope: "openid email profile"
      };
    }

    expectType<never>(config.name); // <- Verifies I checked all the possible `name` uses.

    throw new TypeError("Unknown OAuth 2 config name");
  }

  expectType<never>(config); // <- Verifies I checked all the possible `type` uses.

  throw new TypeError("Unknown config type");
}
```

This example is code I wrote but if I had expanded `Config` before `expectType`, the compiler would have still accepted this code as valid because all it is all typed correctly, it's a programmer error that I didn't check all the possible names available. I just want to be reminded when I change something like `Config["name"] === 'google' | 'github' | 'facebook'` now that it'll fail because I need to exhaust `facebook` in my checks.

Edit: `ts-expect` has no runtime, and I explicitly want to strip it from the runtime, but it helps me catch things that would be considered runtime logic bugs.

**Comment by blakeembrey** [comment]
My bad, seems `shift + enter` causes "close and comment" to be triggered 😄

**Comment by johnnyreilly** [comment]
That's clearer @blakeembrey. I recommend harvesting this conversation to update the readme 😄

So is the second case effectively an alternative way to do an exhaustive switch test? i.e. as described here:

http://ideasintosoftware.com/exhaustive-switch-in-typescript/

**Comment by blakeembrey** [comment]
@johnnyreilly That's a great example and yes! You'd just do `expectType<never>(value)` but it serves the exact same purpose.

**Comment by LongTengDao** [comment]
To confirm a value's type without declaring a new variable:

```ts
var check :string = value_to_check;
```

```ts
check<string>(value_to_check);
```

Which is pure, and will be removed while compiling...?

(If I guess right...)

**Comment by OliverJAsh** [comment]
Hi @blakeembrey! How would you do the equivalent of dtslint’s `$ExpectError` comment but with this library? We are looking at using this tool to write tests for our types, but we need the ability to assert errors too, e.g.

``` ts
const fn = (s: string) => s;
fn(1) // $ExpectError
```

**Comment by blakeembrey** [comment]
@OliverJAsh Unfortunately the only way to do that in TypeScript is by using something like:

```ts
expectType<TypeOf<[1], Parameters<typeof fn>>(false);
```

**Comment by blakeembrey** [comment]
> Which is pure, and will be removed while compiling...?

Unfortunately it won't be removed while compiling today unless you use the (unreleased) transformer. However, the function itself is actually 100% empty so will add no overhead anyway.

**Comment by rhyek** [comment]
How are you supposed to run these tests? I'm guessing just run them against `tsc`? A simple example in the README would be very helpful for someone looking into several options for this type of problem.

**Comment by blakeembrey** [comment]
It’s not super clear what you’d want, do you want me to tell people in the README how to write tests or compile TypeScript? It seems a bit out of scope, but I can try if I can understand where you got stuck. Was it the idea that you need typescript to type check? Personally I’ve never done anything special here, I just use the typescript compiler or TS Jest and both are type checking.
